# Generated by Django 6.0.7 on 2026-07-12 10:23

from django.db import migrations, models

DEFAULT_ACCESS = {
    "fleet_manager": {"fleet": "full", "drivers": "full", "trips": "full", "fuel": "full", "analytics": "full"},
    "dispatcher": {"fleet": "none", "drivers": "none", "trips": "full", "fuel": "none", "analytics": "none"},
    "safety_officer": {"fleet": "none", "drivers": "full", "trips": "none", "fuel": "none", "analytics": "none"},
    "financial_analyst": {"fleet": "none", "drivers": "none", "trips": "none", "fuel": "full", "analytics": "full"},
}


def seed_role_permissions(apps, schema_editor):
    RolePermission = apps.get_model("users", "RolePermission")
    rows = [
        RolePermission(role=role, module=module, access=access)
        for role, modules in DEFAULT_ACCESS.items()
        for module, access in modules.items()
    ]
    RolePermission.objects.bulk_create(rows)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot_name', models.CharField(default='Main Depot', max_length=100)),
                ('currency', models.CharField(default='INR (₹)', max_length=20)),
                ('distance_unit', models.CharField(default='Kilometers', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('fleet_manager', 'Fleet Manager'), ('dispatcher', 'Dispatcher'), ('safety_officer', 'Safety Officer'), ('financial_analyst', 'Financial Analyst')], max_length=20)),
                ('module', models.CharField(choices=[('fleet', 'Fleet'), ('drivers', 'Drivers'), ('trips', 'Trips'), ('fuel', 'Fuel & Expenses'), ('analytics', 'Analytics')], max_length=20)),
                ('access', models.CharField(choices=[('full', 'Full'), ('view', 'View'), ('none', 'No Access')], default='none', max_length=10)),
            ],
            options={
                'unique_together': {('role', 'module')},
            },
        ),
        migrations.RunPython(seed_role_permissions, noop),
    ]
