# Generated by Django 6.0.7 on 2026-07-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('inactive', 'Inactive')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_shop', 'In Shop'), ('retired', 'Retired')], default='active', max_length=20)),
                ('cargo_capacity', models.IntegerField(help_text='Capacity in kg')),
            ],
        ),
    ]
