# Generated by Django 6.0.7 on 2026-07-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_fuellog_maintenancelog_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='region',
            field=models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('central', 'Central')], default='north', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('truck', 'Truck'), ('bus', 'Bus'), ('van', 'Van'), ('car', 'Car'), ('other', 'Other')], default='truck', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_trip', 'On Trip'), ('in_shop', 'In Shop'), ('retired', 'Retired')], default='active', max_length=20),
        ),
    ]
