# Generated by Django 6.0.7 on 2026-07-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehicle_region_vehicle_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='acquisition_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer',
            field=models.PositiveIntegerField(default=0, help_text='Odometer reading in km'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('in_shop', 'In Shop'), ('retired', 'Retired')], default='available', max_length=20),
        ),
    ]
