# Generated by Django 6.0.7 on 2026-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_vehicle_acquisition_cost_vehicle_odometer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_distance_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Planned distance in km', max_digits=8),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
