# Generated by Django 6.0.7 on 2026-07-12 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_maintenancelog_resolved_trip_planned_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total revenue generated by this vehicle', max_digits=12),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='date_logged',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ExpenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('toll', 'Toll'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_logged', models.DateField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_logs', to='fleet.vehicle')),
            ],
        ),
    ]
