# Generated by Django 6.0.7 on 2026-07-12 10:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_vehicle_revenue_alter_fuellog_date_logged_expenselog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='revenue',
        ),
        migrations.CreateModel(
            name='RevenueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date_logged', models.DateField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_logs', to='fleet.vehicle')),
            ],
        ),
    ]
