# Generated by Django 6.0.7 on 2026-07-12 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_remove_vehicle_revenue_revenuelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drivers', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='driver',
            name='employee_id',
            field=models.CharField(default='TEMP-000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('available', 'On Duty'), ('on_trip', 'On Trip'), ('inactive', 'Inactive')], default='available', max_length=20),
        ),
    ]
